apiVersion: v1
kind: Pod
metadata:
  name: webapp
  labels:
    name: webapp
    component: frontend 
spec:
  containers:
  - name: web-portal
    image: rslim087/kubernetes-course-grade-submission-portal
    resources:
      requests: 
        memory: "128Mi"
        cpu: "200m"
      limits:
        memory: "128Mi"
        cpu: "500m"
    ports:
      - containerPort: 5001

apiVersion: v1
kind: Pod
metadata:
  name: webapp-health-checker
  labels:
    name: webapp-health-checker
    component: frontend 
spec:
  containers:
  - name: web-portal-health-checker
    image: rslim087/kubernetes-course-grade-submission-portal-health-checker


